name: Package Swift Project

on:
  push:
    branches:
      - main  # Branch to run SPM

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '6.0'

    - name: Build package
      run: swift build

    - name: Run tests
      run: swift test