name: Package Swift Project

on:
  push:
    branches:
      - master  # Branch to run SPM
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Create Package.swift
      run: |
        cat <<EOF > Package.swift
        // swift-tools-version:5.3
        import PackageDescription

        let package = Package(
            name: "componentsUI",
            platforms: [
               .macOS(.v15),  .iOS(.v15)
            ],
            products: [
                .library(
                    name: "componentsUI",
                    targets: ["componentsUI"]),
            ],
            dependencies: [
                .package(url: "https://github.com/Swinject/Swinject.git", from: "2.9.1")
            ],
            targets: [
                .target(
                    name: "componentsUI",
                    dependencies: ["Swinject"],
                    path: "Sources"),
                .testTarget(
                    name: "componentsUITests",
                    dependencies: ["componentsUI"],
                    path: "Tests"),
            ]
        )
        EOF

    - name: Build package
      run: swift build

    - name: Run tests
      run: swift test